const mongoose=require('mongoose')
const userSchema=mongoose.Schema({
    username:{
        type:String,
        required:true,
        minLength:5,
        maxLength:20,
        unique:true
    },
    password:{
        type:String,
        required:true,
        minLength:8,
        maxLength:100,
    },
    email:{
        type:String,
        required:true,
        minLength:5,
        maxLength:50,
    },
    profilePicture:{
        type:String,
        default:""
    },
    coverPicture:{
        type:String,
        default:""
    },
    followers:{
        type:Array,
        default:[]
    },
    followings:{
        type:Array,
        default:[]
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    desc:{
        type:String,
        maxLength:50,
    },
    city:{
        type:String,
        maxLength:50
    },
    from:{
        type:String,
        maxLength:50
    },
    relationship:{
        type:Number,
        enum:[1,2,3]
    }

},{timestamps:true})

const userCollection=mongoose.model('User',userSchema)
module.exports=userCollection